language: go
go:
  - 1.x
  - tip
env:
  - ETCD_VERSION=3.3.1
services:
  - redis
before_install:
  # install etcd
  - wget https://github.com/coreos/etcd/releases/download/v${ETCD_VERSION}/etcd-v${ETCD_VERSION}-linux-amd64.tar.gz
  - tar xzf etcd-v${ETCD_VERSION}-linux-amd64.tar.gz
  - sudo mv etcd-v${ETCD_VERSION}-linux-amd64/etcd /bin/
  - sudo mv etcd-v${ETCD_VERSION}-linux-amd64/etcdctl /bin/
  - unset ETCD_VERSION
  - etcd &
install:
  - make build
  - sudo make install
script:
  - make test
  - make integration
